# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b40bb8ac0363f8d64d07a8a2c1abc08e87ff5a6c377f92846476dbc57e530dac76cf78471db8d2357afeeae11c3edf6524caeeee810a646cd4b767d7a4dd722e

test:
  secret_key_base: 9e7a9c03e3e6551227ff2d5b329da91ac5dd1d944a0970b75aa0e48cb864cfccc98c7cc774b63508ac2d49e1420671fcf647d219393f5fe6a9aad4e1da41e772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
